README.md, lib/manageiq/providers/ibm_power_hmc/engine.rb
Prepare initial third party services
=> Prepare initial third party services

manageiq-providers-ibm_power_hmc.gemspec
=> Fix plugin name acronyms 2

app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
To get virtual switch displayed on the screen, go to Compute > infrastructure > Hosts > <your managed system> / Network:
=> Adding virtual switch and virtual lans implementation

app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
=> Move add_target and references to core collector

app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
part of ManageIQ/manageiq#21573
=> converting supported_for_create to supports :create

app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/host.rb
Required for: https://github.com/ManageIQ/manageiq/pull/21597
=> Add missing Host subclass under PowerHmc

app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher/stream.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/storage.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
Recreate new PR for https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/24
=> SharedStoragePool inventory

app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb, manageiq-providers-ibm_power_hmc.gemspec
Work in progress 
We add virtual processors and entitled processors in the LPAR inventory.
We also plan to implement whether the VM is dedicated or shared.
=> Adding procs inventory

manageiq-providers-ibm_power_hmc.gemspec
Pick up fix to handle
`uninitialized constant IbmPowerHmc::SharedFileSystemFile` issue
=> Update ibm_power_hmc gem to 0.8.8

manageiq-providers-ibm_power_hmc.gemspec
Includes new `SharedFileSystemFile` class definition.
=> Update ibm_power_hmc gem to 0.9.0

app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision/cloning.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision/state_machine.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision_workflow.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb, content/miq_dialogs/miq_provision_ibm_power_hmc_dialogs_clone_to_vm.yaml, content/miq_dialogs/miq_provision_ibm_power_hmc_dialogs_template.yaml, manageiq-providers-ibm_power_hmc.gemspec, spec/models/manageiq/providers/ibm_power_hmc/infra_manager/provision_workflow_spec.rb, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
Aim: provision an LPAR from an HMC template.
First step is to be able to provision an LPAR with minimum customization (LPAR name).
=> Initial VM provisioning from template work

app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
Continuing to remove uneeded memoization.
@miq-bot add-label bug
@miq-bot add-label najdorf/yes?
@miq-bot assign @agrare
=> Removing Memoization

app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb, spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
See https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/issues/78.
=> improve operating system name parser

app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
The HMC provides us with the list of physical volumes (SAS, FC) attached to the VIOSes (same as `lspv` ioscsli command).
Add them to the inventory.
=> store vios physical volumes in the inventory

app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
Bug introduced in https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/89
=> fix error path when collecting storage pools

app/models/manageiq/providers/ibm_power_hmc/infra_manager/host.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/vios.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Use HMC terms:
"Host" => "Managed System"
"Virtual Machine" => "Partition" (generic) or "Virtual I/O Server"
=> implement display_name for hosts and vms

app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb, manageiq-providers-ibm_power_hmc.gemspec
=> collect SEA and trunk adapters from VIOSes

app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb, spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_host_0685d4a6-2021-3044-84e3-59f44e9cc5d7.yml, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_resource_pool_cpu__d47a585d-eaa8-3a54-b4dc-93346276ea37_c41d8844-1d39-3512-944d-50f58de2d42d.yml, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_resource_pool_mem__d47a585d-eaa8-3a54-b4dc-93346276ea37_557f7755-a4dc-30de-816d-387f42dd8fd3.yml
Missing implementation in TargetCollection class meant Collector implementation was called resulting in Resource Pool being removed from Inventory.
=> Fix targeted collection for memory Resource Pools

app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb, manageiq-providers-ibm_power_hmc.gemspec, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_lpar_646AE0BC-CF06-4F6B-83CB-7A3ECCF903E3.yml, spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_vios_4165A16F-0766-40F3-B9E2-7272E1910F2E.yml
Having the VFC client adapter or FC port WWPNs can be quite useful.
VFC client adapter:
Physical FC port:
=> collect fc ports and vfc client adapters

app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb, app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision_workflow.rb, spec/models/manageiq/providers/ibm_power_hmc/infra_manager_spec.rb
=> Enable VM provisioning through catalog item

app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb, spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
Depends on:
- https://github.com/ManageIQ/manageiq-schema/pull/708
=> Use new resource pool cpu_core_* columns

app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
These are all internal helper methods that do not need to be public
=> Make internal EventTargetParser methods private
