ManageIQ/manageiq-providers-ibm_power_hmc

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- manageiq-providers-ibm_power_hmc.gemspec
Another type of ethernet adapters.
These do not have UUIDs so we use the MAC address as the unique ID instead.
> Add Host Ethernet Adapter Logical Ports to inventory

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- manageiq-providers-ibm_power_hmc.gemspec
This adds HMC partition templates to the inventory. So far it only records memory and operating system information.
Event-based targeted refresh not functional at this time.
> Add templates

- app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
These were being created as `ManageIQ::Providers::InfraManager::Template` types
> Fix Templates not subclassed under IbmPowerHmc

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
Use "ibm_power_hmc" vendor name to match the existing decorator icon.
Depends on: https://github.com/ManageIQ/manageiq/pull/21701
> Fix vendor references

- app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
When an EMS is being edited the password is not sent back down unless it is changed so we have to look it up when verifying credentials.
This was failing because of an undefined variable `authtype`.
> Fix verify_credentials for an existing EMS

- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
If an 'IbmPowerHmc::Connection::HttpError' exception is encountered
during inventory collection it shouldn't be ignored. When ignored
something like a timeout can cause the collector to "successfully"
collect nothing and give the user an empty inventory with no error
messages.
> Raise HttpError after logging error

- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
Other methdods in this module iterate over 'ems_ref' of resources, but
SSPS collect everything with a single call to 'connection.ssps'. The log
message was probably copied from the other block without removing the
'ems_ref'.
> Remove misplaced 'ems_ref' from log message

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
If 'vmm_vendor' is not set the UI displays a question mark icon and
"Unknown" in the VMM Information.
Depends on:
- https://github.com/ManageIQ/manageiq-decorators/pull/69
- https://github.com/ManageIQ/manageiq/pull/21776
> Set host 'vmm_vendor' to display HMC icon

- app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/host.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
- manageiq-providers-ibm_power_hmc.gemspec
- spec/factories/advanced_setting.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/host_spec.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/pcm_preferences.xml
Retrieve Performance and Capacity Monitor preferences for each Host and store it so ManageIQ does not try to collect metrics for a host and its VMs if there is nothing to collect.
> Check if PCM is enabled on host

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb
The Template view is leaving Template cloning enabled even though this is not supported in this version. Clicking on this menu item leaves the user with a blank form.
The menu item is checking the list of supported features of the record
https://github.com/ManageIQ/manageiq-ui-classic/blob/najdorf/app/helpers/application_helper/button/generic_feature_button.rb
https://github.com/ManageIQ/manageiq-ui-classic/blob/c98fb3d7091db45a707b332ab7b7949119c2e38a/app/helpers/application_helper/toolbar/x_miq_template_center.rb#L98
https://github.com/ManageIQ/manageiq-ui-classic/blob/c98fb3d7091db45a707b332ab7b7949119c2e38a/app/helpers/application_helper.rb#L203
By explicitly declaring Template cloning as not supported, the menu item is disabled.
> [Najdorf] Explicitly declare Template cloning as not supported

- content/miq_dialogs/miq_provision_ibm_power_hmc_dialogs_clone_to_template.yaml
- content/miq_dialogs/miq_provision_ibm_power_hmc_dialogs_template.yaml
Psych warns:
~/.rubies/ruby-2.7.6/lib/ruby/2.7.0/psych/visitors/to_ruby.rb:106: warning: character class has '-' without escape: /\A(?:[A-Za-z0-9-_]+)\Z/
~/.gem/ruby/2.7.6/gems/activesupport-6.1.6.1/lib/active_support/core_ext/marshal.rb:8: warning: character class has '-' without escape: /\A(?:[A-Za-z0-9-_]+)\Z/
The fix here is to just put the '-' at the end of the character class.
Otherwise, the character class is unsure if the '-' is to be used as a
range indicator or not. At the end it is unambiguously not a range
indicator.
> Fix Psych warning regarding '-'

- app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
- config/settings.yml
- manageiq-providers-ibm_power_hmc.gemspec
When hosts have lost their connection to an HMC, the Managed System(s) APIs will take 2+ minutes to respond. The default response timeout for the rest-client gem is 60 seconds. Adding a user configurable setting to override the API request timeout allows inventory refresh to succeed, even when the responses are slow due to disconnected systems (or possible other reasons).
~The default value of 180 seconds should be enough to allow inventory refresh to pass in most cases, but still fail in a timely manner in the event of a "real" timeout.~
After further discussion, I set the default timeout value to 60 seconds. The intention is to leave existing behavior unchanged _unless_ the user changes the setting introduced here.
Depends on:
- https://github.com/IBM/ibm_power_hmc_sdk_ruby/pull/82
> Add setting to adjust HMC API request timeout

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
When we increase the timeout in order to receive all CECs, we gather hosts with `no connection` state.
This creates a bug because in that case we don't have PCM informations
This patchs is supposed to resolve it
Signed-off-by: HANRIAT Calliste <hanriat.calliste@ibm.com>
> Handle case where PCM enabled setting is not available

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
The HMC does not give us visibility above the networking data link layer, so we are only able to display MAC address for each network interface. 
However, the HMC knows one of the IP address of the VM in order to communicate with it through Resource Monitoring Control. In many cases, this would be the IP address the VM is known by, so it has been suggested the provider should display this address in ManageIQ. Subnet mask is not available.
Screen captures after modification:
> Insert IP address used by RMC as a VM IP address

- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
The idea here is to refresh LPARs that have disks attached to the VIOS when the VIOS is updated.
Disks coming from other VIOSes are queried from DB.
We manage multi-pathing using the location code of the disk as a list of client adapter names.
> Collect LPAR disks using VSCSI mappings

- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
Introduced by #89
This results in a "wrong number of parameters" error and causes targeted collection for storages to fail.
> Fix bug in targeted collection

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
The HMC displays physical adapters of the managed systems:
With this change, the physical adapters show up like this in MIQ UI:
> Collect host hardware devices

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher/stream.rb
There is a possibility that we never exit the poll loop if no events are ever read from the HMC:
https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/blob/9470024cba887d6e31b11abe56ec632f2dabcb55/app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher/stream.rb#L23-L29
This needs to be fixed by checking `@stop_polling` outside of the `next_events` loop.
Also, the HMC already waits about 10 seconds before returning if there is no event, so take that into account in the poll interval, otherwise we may end up waiting more than `10+@poll_sleep` seconds.
> Fix poll sleep interval in event catcher and make sure we can exit the poll loop

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- manageiq-providers-ibm_power_hmc.gemspec
In PowerVM, it is possible to assign physical I/O adapters to a partition (VIOS or LPAR) using the IOMMU.
The HMC shows the physical I/O adapters attached to a partition like this:
With this change, we see them from MIQ like so:
> Add physical I/O adapters to VMs

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Renaming was only supported for LPARs (because the HMC SDK does not have a `rename_vios` method).
The HMC SDK now exports a generic `modify_object` method that allows to modify any attribute of any supported object types.
> use new modify_object api to rename LPARs and VIOSes

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
Currently, when a VM description is changed in MIQ, it is overridden by the next VM refresh.
> supports set_description for VMs

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher/stream.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser.rb
- config/settings.yml
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_parser_spec.rb
The HMC provider currently records all HMC events in the `event_streams`, resulting in this table growing out of control with a numbers of daily new entries in the order of thousands.
A very large part of these entries are of type INVALID_URI, which only means the cache has been cleared on the HMC side for a given object.
Proposed solution:
- Limit recorded events to CREATE_URI, MODIFY_URI and DELETE_URI
- Fill in message field to have more information on what actually changed
- Downgrade all events from 'critical' level to 'detail'
Event example:
> Filter out irrelevant HMC events

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
A deprecation warning was added in this commit:
https://github.com/ManageIQ/inventory_refresh/commit/e599e73ec5244b83bce38dcb3be90855b0a02f4a
if `lazy_find` is called with a hash for options.
This `lazy_find` call was introduced by PR https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/105.
```
DEPRECATION WARNING: Passing a hash for options is deprecated and will be removed in an upcoming release. (called from vlan_by_tag at /home/runner/work/manageiq-providers-ibm_power_hmc/manageiq-providers-ibm_power_hmc/app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb:492)
```
> fix deprecation warning in lazy_find with options

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/ignored_usertask.xml
HMC events of type "UserTask" that have their status set to something other than "Completed" are causing are not handled well by the event target parser. This generate an error in evm.log like this one:
```
[----] E, [2022-11-09T14:39:47.411859 #218489:1705c] ERROR -- evm: MIQ(MiqAeEngine.deliver) Error delivering {:event_id=>369279, :event_stream_id=>369279, :event_type=>"ADD_URI", "User::user"=>1, "EventStream::event_stream"=>369279} for object [EmsEvent.369279] with state [] to Automate: no implicit conversion of nil into Array
```
Actual error is:
```
2: from /home/padmin/manageiq-providers-ibm_power_hmc/app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb:48:in `parse'
1: from /home/padmin/manageiq-providers-ibm_power_hmc/app/models/manageiq/providers/ibm_p …
```
> Errors in log due to some HMC Usertask events not handled properly

- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
Minor change to Refresher specs: check that expected Storage object is in Inventory following a global and a targeted refresh.
> Verify storage object in global & targeted refresh specs

- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
- spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher.yml
- spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_lpar_646AE0BC-CF06-4F6B-83CB-7A3ECCF903E3.yml
- spec/vcr_cassettes/manageiq/providers/ibm_power_hmc/infra_manager/refresher_vios_4165A16F-0766-40F3-B9E2-7272E1910F2E.yml
The HMC allows the creation of what it calls "groups" which are basically just labels for LPARs, VIOSes and managed systems.
An LPAR, a VIOS or a managed system can be part of several groups at the same time.
Groups have a description and a color assigned to them.
LPAR view:
Groups view:
With these changes, labels appear in MIQ UI like so:
> hmc groups as vm labels

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar_spec.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/template_spec.rb
Supported functionalities for VMs & Templates of type "provisionning", "clone" and "publish" are currently set without conditions. The UI therefore lets user initiate such a request on archived VMs & Templates which inevitably results in this error:
Proposed fix it to check at the instance level that VM or Template is not archived (i.e. it has an EMS), so the UI rejects requets.
At best, the menu item is disabled, like so:
At the very least, the request fails in a clean way:
> Restrict supported functionalities for archived VMs & Templates

- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector/target_collection.rb
Running `bundle exec rubocop` leads to a bunch of `Layout/RescueEnsureAlignment` rubocop offenses that are not checked by CI.
> fix rubocop Layout/RescueEnsureAlignment errors

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm/reconfigure.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- manageiq-providers-ibm_power_hmc.gemspec
Allow to modify memory and number of virtual processors of an LPAR or a VIOS (using DR if LPAR is running and RMC is active).
Allow to add/remove client network adapters to/from LPARs.
Disks reconfiguration is not supported by this PR.
> add vm reconfiguration for cpu, memory and network

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- manageiq-providers-ibm_power_hmc.gemspec
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
Following addition of shared memory pools to inventory (#115), add advanced setting to VMs and Templates, either set to "shared" or "dedicated", in a similar way to processors.
> Add memory_type advanced setting (dedicated or shared) for VM & Templates

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
- manageiq-providers-ibm_power_hmc.gemspec
> implement raw_destroy for LPARs

- app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/media_repository.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/persister/infra_manager.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
With PowerVM, each VIOS can have a virtual media repository containing ISO images that can then be mapped to LPARs via VSCSI:
Depends on:
> collect media repositories as ISO storages

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb
The term "ems" is an insider term. This commit uses the same "not connected" text that we use in core.
See also https://github.com/ManageIQ/manageiq/pull/22284#discussion_r1060844227
> Use better text for user-facing errors

- app/models/manageiq/providers/ibm_power_hmc/inventory/parser/infra_manager.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/refresher_spec.rb
IBM PowerVM hypervisor (PHYP) is the correct product name.
Example:
Note that the PowerVM hypervisor (commonly referred to as PHYP) doesn't have it's own icon. It is a fundamental component of PowerVM, though, so using the magic of [`OperatingSystem.normalize_os_name`](https://github.com/ManageIQ/manageiq/blob/master/app/models/operating_system.rb?plain=1#L76C12-L84) this PowerVM icon will be displayed.
Depends on:
- https://github.com/ManageIQ/manageiq-decorators/pull/89
- https://github.com/ManageIQ/manageiq/pull/22523
> Use the correct PHYP product name

- content/miq_dialogs/miq_provision_ibm_power_hmc_dialogs_template.yaml
The 'allowed_templates' method is a core method to generate a list of
templates for the selection dialog. This is explicitly necessary when
creating a catalog item since the user selects the template after
entering into the request dialog (in contrast to the 'Lifecycle >
Provision VMs using this Template' which auto-selects the template).
Without this, the following exception is raised when attempting to
definite a Power HMC VM provision catalog item:
FATAL -- : Error caught: [NoMethodError] undefined method `any?' for nil:NilClass
> Fix provisioning dialog 'src_vm_id' method

- app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
Port 443 is the preferred default port to access the HMC API. While port
12443 is also open by default in the latest HMC (v10) I'm told that may
change.
> Change default API port to 443

- app/models/manageiq/providers/ibm_power_hmc/infra_manager.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_catcher.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/metrics_collector_worker.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/provision.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/refresh_worker.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/collector.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/parser.rb
- app/models/manageiq/providers/ibm_power_hmc/inventory/persister.rb
Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854
> Drop require_nested and include_concern

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/host.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/template.rb
- app/models/manageiq/providers/ibm_power_hmc/infra_manager/vm.rb
part of:
- https://github.com/ManageIQ/manageiq/pull/22898
Deprecating `unsupported_reason_add`. Returning the string instead
Note, these are all the same:
```ruby
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports_feature2?
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports?(:feature2)
unsupported_reason(:feature2) unless supports?(:feature2)
unsupported_reason(:feature2)
```
> drop unsupported_reason_add

- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/lpar_spec.rb
part of https://github.com/ManageIQ/manageiq/pull/22883
> supports_start? => supports?(:start)

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/host.rb
Part of https://github.com/ManageIQ/manageiq/pull/22898 (as a followup)
Introduced by https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/153
You can not have a return in a block. It causes a LongJump error Besides, it tries to return from inside the calling block - not what we want.
> Remove return from supports block

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/logical_partition_invalid_uuid.xml
The HMC uses `88888888-8888-8888-8888-888888888888` to indicate an unassigned LPAR UUID. This is an error state, but we've seen it occur in a test environment so I'm adding a special case for it to trigger a full ems refresh.
> Refresh entire provider for special LPAR UUID

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/logical_partition_invalid_event_data.xml
This isn't the greatest regular expression of all time :D but it passes the specs.
The URLs for events that we get from the specs are:
```
https://te.st:12443/rest/api/uom/ManagedSystem/e4acf909-6d0b-3c03-b75a-4d8495e5fc49/VirtualSwitch/74CC38E2-C6DD-4B03-A0C6-088F7882EF0E
https://coophmc2:12443/rest/api/uom/ManagedSystem/d47a585d-eaa8-3a54-b4dc-93346276ea37/SharedMemoryPool/557f7755-a4dc-30de-816d-387f42dd8fd3
https://te.st:12443/rest/api/uom/ManagedSystem/977848c8-3bed-360a-c9d2-ae4b7e46b5d1
https://te.st:12443/rest/api/uom/UserTask/1d43a4a6-903c-46f8-865d-a356559bb17f
https://te.st:12443/rest/api/uom/Cluster/c1e50c27-888c-3c4d-8d4a-53a3768ea250
https://coophmc2:12443/rest/api/uom/ManagedSystem/d47a585d-eaa8-3a54-b4dc-93346276ea37/SharedProcessorPool/27aae064-2855-39a0-b4e6-e3c9b5572036 …
```
> Parse the event url with Regex not split

- app/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/event_target_parser_spec.rb
- spec/models/manageiq/providers/ibm_power_hmc/infra_manager/test_data/logical_partition_profile_invalid_uuid.xml
Follow up to #164 (and #167).
When testing #164 I noticed the LPAR delete event URL also included `LogicalPartition` information, which prevented the event target parser from coming up with a target. For example:
```
https://te.st:12443/rest/api/uom/ManagedSystem/e4acf909-6d0b-3c03-b75a-4d8495e5fc49/LogicalPartition/88888888-8888-8888-8888-888888888888/LogicalPartitionProfile/123abc45-6789-0123-45de-67fa890bc123
```
> Fix event parsing
